### ISSUE TITLE
White box in active ads

### ISSUE THREAD

**Issue by mdczaplicki** [pawelos076232/OLX-QuiteDark#1]
![image](https://cloud.githubusercontent.com/assets/9108586/24862986/5cfade82-1dff-11e7-9bc2-21e251692b0f.png)

It happens on polish version of OLX (maybe other too)

**Comment by pawelos076232** [comment]
Thanks for reporting!
Please, make an update. It should already work.

Jak coś, możesz mi zgłaszać również po polsku :smiley:

**Comment by mdczaplicki** [comment]
![image](https://cloud.githubusercontent.com/assets/9108586/24914690/3dd9c9ce-1ed5-11e7-9056-747a3d2e4f9a.png)
Jeszcze został taki pasek między przedmiotami :)

**Comment by pawelos076232** [comment]
Zrobione w wersji 0.2.7
